### ISSUE TITLE
SVG icons

### ISSUE THREAD

**Issue by GoogleCodeExporter** [tieugene/dasist#58]
```
http://www.flaticon.com/
```

Original issue reported on code.google.com by `ti.eug...@gmail.com` on 7 Dec 2014 at 7:35

**Comment by tieugene** [comment]
svg slim: just replace 1184q0 w/ 656q0

**Comment by tieugene** [comment]
http://fontawesome.io/
https://github.com/encharm/Font-Awesome-SVG-PNG
